export const CREATE_COURSE_CATEGORY_REQUEST ="CREATE_COURSE_CATEGORY_REQUEST";
export const CREATE_COURSE_CATEGORY_SUCCESS ="CREATE_COURSE_CATEGORY_SUCCESS";
export const CREATE_COURSE_CATEGORY_FAIL ="CREATE_COURSE_CATEGORY_FAIL";

// ----all course category-------------


export const ALL_COURSE_CATEGORY_REQUEST ="ALL_COURSE_CATEGORY_REQUEST";
export const ALL_COURSE_CATEGORY_SUCCESS ="ALL_COURSE_CATEGORY_SUCCESS";
export const ALL_COURSE_CATEGORY_FAIL ="ALL_COURSE_CATEGORY_FAIL";

//--delete course category-------------
export const DELETE_COURSE_CATEGORY_REQUEST ="DELETE_COURSE_CATEGORY_REQUEST";
export const DELETE_COURSE_CATEGORY_SUCCESS ="DELETE_COURSE_CATEGORY_SUCCESS";
export const DELETE_COURSE_CATEGORY_FAIL ="DELETE_COURSE_CATEGORY_FAIL";
//--update course category-------------

export const UPDATE_COURSE_CATEGORY_REQUEST ="UPDATE_COURSE_CATEGORY_REQUEST";
export const UPDATE_COURSE_CATEGORY_SUCCESS ="UPDATE_COURSE_CATEGORY_SUCCESS";
export const UPDATE_COURSE_CATEGORY_FAIL ="UPDATE_COURSE_CATEGORY_FAIL";

//single view course categoryy

export const SINGLE_COURSE_CATEGORY_REQUEST ="SINGLE_COURSE_CATEGORY_REQUEST";
export const SINGLE_COURSE_CATEGORY_SUCCESS ="SINGLE_COURSE_CATEGORY_SUCCESS";
export const SINGLE_COURSE_CATEGORY_FAIL ="SINGLE_COURSE_CATEGORY_FAIL";



